In [ ]:
"""Importa a biblioteca fastf1 para acessar dados da Fórmula 1."""

import fastf1

In [ ]:
"""Obtém a sessão da corrida (Race) do GP 7 da temporada de 2021 usando a biblioteca fastf1."""

session = fastf1.get_session(2021, 7, 'R')

In [ ]:
"""Carrega os dados da sessão selecionada para permitir a análise das informações da corrida."""

session.load()

core           INFO 	Loading data for French Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 33 completed the race distance 00:00.047000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '11', '77', '4', '3', '10', '14', '5', '18', '55', '63', '22', '31', '99', '16', '7', '6', '47', '9']

In [ ]:
"""Importa a biblioteca pandas para manipulação de dados."""
import pandas as pd

"""Configura o pandas para exibir todas as colunas ao mostrar DataFrames."""
pd.set_option('display.max_columns', None)

"""Exibe os resultados da sessão carregada da Fórmula 1."""
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
33,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,0600EF,red_bull,Max,Verstappen,Max Verstappen,https://www.formula1.com/content/dam/fom-websi...,,1.0,1,1.0,NaT,NaT,NaT,0 days 01:27:25.770000,Finished,26.0,53.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,https://www.formula1.com/content/dam/fom-websi...,,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.904000,Finished,18.0,53.0
11,11,S PEREZ,PER,perez,Red Bull Racing,0600EF,red_bull,Sergio,Perez,Sergio Perez,https://www.formula1.com/content/dam/fom-websi...,,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:08.811000,Finished,15.0,53.0
77,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,https://www.formula1.com/content/dam/fom-websi...,,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:14.618000,Finished,12.0,53.0
4,4,L NORRIS,NOR,norris,McLaren,FF9800,mclaren,Lando,Norris,Lando Norris,https://www.formula1.com/content/dam/fom-websi...,,5.0,5,8.0,NaT,NaT,NaT,0 days 00:01:04.032000,Finished,10.0,53.0
3,3,D RICCIARDO,RIC,ricciardo,McLaren,FF9800,mclaren,Daniel,Ricciardo,Daniel Ricciardo,https://www.formula1.com/content/dam/fom-websi...,,6.0,6,10.0,NaT,NaT,NaT,0 days 00:01:15.857000,Finished,8.0,53.0
10,10,P GASLY,GAS,gasly,AlphaTauri,2B4562,alphatauri,Pierre,Gasly,Pierre Gasly,https://www.formula1.com/content/dam/fom-websi...,,7.0,7,6.0,NaT,NaT,NaT,0 days 00:01:16.596000,Finished,6.0,53.0
14,14,F ALONSO,ALO,alonso,Alpine,0090FF,alpine,Fernando,Alonso,Fernando Alonso,https://www.formula1.com/content/dam/fom-websi...,,8.0,8,9.0,NaT,NaT,NaT,0 days 00:01:17.695000,Finished,4.0,53.0
5,5,S VETTEL,VET,vettel,Aston Martin,006F62,aston_martin,Sebastian,Vettel,Sebastian Vettel,https://www.formula1.com/content/dam/fom-websi...,,9.0,9,12.0,NaT,NaT,NaT,0 days 00:01:19.666000,Finished,2.0,53.0
18,18,L STROLL,STR,stroll,Aston Martin,006F62,aston_martin,Lance,Stroll,Lance Stroll,https://www.formula1.com/content/dam/fom-websi...,,10.0,10,19.0,NaT,NaT,NaT,0 days 00:01:31.946000,Finished,1.0,53.0
55,55,C SAINZ,SAI,sainz,Ferrari,DC0004,ferrari,Carlos,Sainz,Carlos Sainz,https://www.formula1.com/content/dam/fom-websi...,,11.0,11,5.0,NaT,NaT,NaT,0 days 00:01:39.337000,Finished,0.0,53.0
63,63,G RUSSELL,RUS,russell,Williams,005AFF,williams,George,Russell,George Russell,https://www.formula1.com/content/dam/fom-websi...,,12.0,12,14.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,2B4562,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,https://www.formula1.com/content/dam/fom-websi...,,13.0,13,0.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
31,31,E OCON,OCO,ocon,Alpine,0090FF,alpine,Esteban,Ocon,Esteban Ocon,https://www.formula1.com/content/dam/fom-websi...,,14.0,14,11.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
99,99,A GIOVINAZZI,GIO,giovinazzi,Alfa Romeo Racing,900000,alfa,Antonio,Giovinazzi,Antonio Giovinazzi,https://www.formula1.com/content/dam/fom-websi...,,15.0,15,13.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
16,16,C LECLERC,LEC,leclerc,Ferrari,DC0004,ferrari,Charles,Leclerc,Charles Leclerc,https://www.formula1.com/content/dam/fom-websi...,,16.0,16,7.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
7,7,K RAIKKONEN,RAI,raikkonen,Alfa Romeo Racing,900000,alfa,Kimi,Räikkönen,Kimi Räikkönen,https://www.formula1.com/content/dam/fom-websi...,,17.0,17,17.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
6,6,N LATIFI,LAT,latifi,Williams,005AFF,williams,Nicholas,Latifi,Nicholas Latifi,https://www.formula1.com/content/dam/fom-websi...,,18.0,18,16.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
47,47,M SCHUMACHER,MSC,mick_schumacher,Haas F1 Team,FFFFFF,haas,Mick,Schumacher,Mick Schumacher,https://www.formula1.com/content/dam/fom-websi...,,19.0,19,15.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
9,9,N MAZEPIN,MAZ,mazepin,Haas F1 Team,FFFFFF,haas,Nikita,Mazepin,Nikita Mazepin,https://www.formula1.com/content/dam/fom-websi...,,20.0,20,18.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0

In [ ]:
"""Salva os resultados da sessão em um arquivo no formato Parquet."""

session.results.to_parquet("data/2021_07_R.parquet")

In [ ]:
"""Lê o arquivo Parquet com os resultados da corrida e carrega em um DataFrame."""

df=pd.read_parquet("data/2021_07_R.parquet")
df

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
index,,,,,,,,,,,,,,,,,,,,,,
33,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,0600EF,red_bull,Max,Verstappen,Max Verstappen,https://www.formula1.com/content/dam/fom-websi...,,1.0,1,1.0,NaT,NaT,NaT,0 days 01:27:25.770000,Finished,26.0,53.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,https://www.formula1.com/content/dam/fom-websi...,,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:02.904000,Finished,18.0,53.0
11,11,S PEREZ,PER,perez,Red Bull Racing,0600EF,red_bull,Sergio,Perez,Sergio Perez,https://www.formula1.com/content/dam/fom-websi...,,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:08.811000,Finished,15.0,53.0
77,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,https://www.formula1.com/content/dam/fom-websi...,,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:14.618000,Finished,12.0,53.0
4,4,L NORRIS,NOR,norris,McLaren,FF9800,mclaren,Lando,Norris,Lando Norris,https://www.formula1.com/content/dam/fom-websi...,,5.0,5,8.0,NaT,NaT,NaT,0 days 00:01:04.032000,Finished,10.0,53.0
3,3,D RICCIARDO,RIC,ricciardo,McLaren,FF9800,mclaren,Daniel,Ricciardo,Daniel Ricciardo,https://www.formula1.com/content/dam/fom-websi...,,6.0,6,10.0,NaT,NaT,NaT,0 days 00:01:15.857000,Finished,8.0,53.0
10,10,P GASLY,GAS,gasly,AlphaTauri,2B4562,alphatauri,Pierre,Gasly,Pierre Gasly,https://www.formula1.com/content/dam/fom-websi...,,7.0,7,6.0,NaT,NaT,NaT,0 days 00:01:16.596000,Finished,6.0,53.0
14,14,F ALONSO,ALO,alonso,Alpine,0090FF,alpine,Fernando,Alonso,Fernando Alonso,https://www.formula1.com/content/dam/fom-websi...,,8.0,8,9.0,NaT,NaT,NaT,0 days 00:01:17.695000,Finished,4.0,53.0
5,5,S VETTEL,VET,vettel,Aston Martin,006F62,aston_martin,Sebastian,Vettel,Sebastian Vettel,https://www.formula1.com/content/dam/fom-websi...,,9.0,9,12.0,NaT,NaT,NaT,0 days 00:01:19.666000,Finished,2.0,53.0
18,18,L STROLL,STR,stroll,Aston Martin,006F62,aston_martin,Lance,Stroll,Lance Stroll,https://www.formula1.com/content/dam/fom-websi...,,10.0,10,19.0,NaT,NaT,NaT,0 days 00:01:31.946000,Finished,1.0,53.0
55,55,C SAINZ,SAI,sainz,Ferrari,DC0004,ferrari,Carlos,Sainz,Carlos Sainz,https://www.formula1.com/content/dam/fom-websi...,,11.0,11,5.0,NaT,NaT,NaT,0 days 00:01:39.337000,Finished,0.0,53.0
63,63,G RUSSELL,RUS,russell,Williams,005AFF,williams,George,Russell,George Russell,https://www.formula1.com/content/dam/fom-websi...,,12.0,12,14.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,2B4562,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,https://www.formula1.com/content/dam/fom-websi...,,13.0,13,0.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
31,31,E OCON,OCO,ocon,Alpine,0090FF,alpine,Esteban,Ocon,Esteban Ocon,https://www.formula1.com/content/dam/fom-websi...,,14.0,14,11.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
99,99,A GIOVINAZZI,GIO,giovinazzi,Alfa Romeo Racing,900000,alfa,Antonio,Giovinazzi,Antonio Giovinazzi,https://www.formula1.com/content/dam/fom-websi...,,15.0,15,13.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
16,16,C LECLERC,LEC,leclerc,Ferrari,DC0004,ferrari,Charles,Leclerc,Charles Leclerc,https://www.formula1.com/content/dam/fom-websi...,,16.0,16,7.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
7,7,K RAIKKONEN,RAI,raikkonen,Alfa Romeo Racing,900000,alfa,Kimi,Räikkönen,Kimi Räikkönen,https://www.formula1.com/content/dam/fom-websi...,,17.0,17,17.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
6,6,N LATIFI,LAT,latifi,Williams,005AFF,williams,Nicholas,Latifi,Nicholas Latifi,https://www.formula1.com/content/dam/fom-websi...,,18.0,18,16.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
47,47,M SCHUMACHER,MSC,mick_schumacher,Haas F1 Team,FFFFFF,haas,Mick,Schumacher,Mick Schumacher,https://www.formula1.com/content/dam/fom-websi...,,19.0,19,15.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0
9,9,N MAZEPIN,MAZ,mazepin,Haas F1 Team,FFFFFF,haas,Nikita,Mazepin,Nikita Mazepin,https://www.formula1.com/content/dam/fom-websi...,,20.0,20,18.0,NaT,NaT,NaT,NaT,+1 Lap,0.0,52.0

In [ ]:
class CollectResults:
    """
    Classe responsável por coletar resultados de corridas da Fórmula 1 utilizando a biblioteca fastf1
    e salvar os dados no formato Parquet para análise posterior.
    """

    def __init__(self, year=[2021, 2022, 2023], modes=['R', 'S']):
        """
        Inicializa a classe com os anos e tipos de sessão que serão coletados.

        Parâmetros:
            year (list): Lista de anos das temporadas de F1.
            modes (list): Tipos de sessão (ex: 'R' para Race e 'S' para Sprint).
        """
        self.years = year
        self.modes = modes
        
    def get_data(self, year, gp, mode)->pd.DataFrame:
        """
        Coleta os dados de uma sessão específica de um GP.

        Parâmetros:
            year (int): Ano da temporada.
            gp (int): Número do Grande Prêmio.
            mode (str): Tipo da sessão ('R' ou 'S').

        Retorno:
            pd.DataFrame: DataFrame com os resultados da sessão.
            Caso a sessão não exista, retorna um DataFrame vazio.
        """
        try:
            session = fastf1.get_session(year, gp, mode)
            
        except ValueError as err:
            return pd.DataFrame()
        
        session._load_drivers_results()
        df = session.results
        df["Mode"] = mode
        
        return df
    
    def save_data(self, df, year, gp, mode):
        """
        Salva os dados coletados em arquivo Parquet.

        Parâmetros:
            df (DataFrame): Dados da sessão.
            year (int): Ano da temporada.
            gp (int): Número do GP.
            mode (str): Tipo da sessão.
        """
        df.to_parquet(f"data/{year}_{gp:02}_{mode}.parquet")
        
    def process(self, year, gp, mode):
        """
        Executa o processo completo para um GP:
        coleta os dados e salva no arquivo.

        Retorno:
            bool: False se o DataFrame estiver vazio, True caso contrário.
        """
        df = self.get_data(year, gp, mode)
        self.save_data(df, year, gp, mode)
        if df.empty:
            return False
        self.save_data(df, year, gp, mode)
        return True
    
    def process_year_modes(self, year):
        """
        Percorre todos os GPs de um determinado ano
        e executa a coleta para cada tipo de sessão.
        """
        for i in range(1, 50):
            for mode in self.modes:
                if not self.process(year, i, mode) and mode == 'R':
                    return
                
    def process_years(self):
        """
        Executa a coleta de dados para todos os anos definidos na classe.
        """
        for year in self.years:
            print(f"Coletando dados do ano {year}")
            self.process_year_modes(year)
            time.sleep(10)

In [90]:
"""Cria uma instância da classe CollectResults definindo os anos e tipos de sessão a serem coletados."""
Collect = CollectResults([2023, 2024, 2025], ["R", "S"])

"""Executa o processo de coleta e salvamento dos dados para todos os anos definidos."""
Collect.process_years()

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for driver_info
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...

KeyboardInterrupt: